FROM node:20-alpine3.18 as builder

WORKDIR /app

ARG API_ENDPOINT NEXT_PUBLIC_API_ENDPOINT GOOGLE_MAPS_API_KEY NEXT_PUBLIC_GOOGLE_MAPS_API_KEY

ENV API_ENDPOINT=${API_ENDPOINT}
ENV NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT}
ENV GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}

COPY package*.json ./
RUN npm install --prodaction
COPY . .
RUN npm run build
EXPOSE 3000
CMD [ "npm","run","start"]
